"use strict";(self.webpackChunk=self.webpackChunk||[]).push([[717],{68300:function(D,d,n){n.r(d),n.d(d,{default:function(){return b}});var l=n(86111),w=n(37666),e={global:"global___qimCX",globalRow:"globalRow___saF3Z",header:"header___KgVbf",main:"main___v6QZW"},c={header:"header___iOwDU",pricetag:"pricetag___fvwuq",pricetagDesc:"pricetagDesc___a_0eg",icon:"icon___JgCCq",merchantHead:"merchantHead___V_pQD",ticketDetailsRow:"ticketDetailsRow___rwzi8"},s={icon_merchant:"icon_merchant___a8EVv",green_icon:"green_icon___yGqnt",orange_icon:"orange_icon___NNx95",blue_icon:"blue_icon___kCPDK"},u=n(68400),v=n.n(u),x=n(1289),a=n(85893),i,g=x.ZP.div(i||(i=v()([`
	padding: 16px;
	background-color: var(--v5-background-medium-contrat);
	border-radius: var(--border-radius);
	&.short-padding{
		padding: 10px 16px;
	}

	&.rounded{
		border-radius: var(--border-radius-rounded);
	}
`]))),j=function(r){var t=r.children,h=r.className,f=h?" ".concat(h):"";return(0,a.jsx)(g,{className:"".concat(f),children:t})},m=j,_=function(){return(0,a.jsx)("div",{className:"standard-header ".concat(c.header),children:(0,a.jsxs)("header",{className:"container-fluid",children:[(0,a.jsxs)("div",{className:"row g-0 merchant-head align-items-center ".concat(c.merchantHead),children:[(0,a.jsx)("div",{className:"col-3 ".concat(c.icon," ").concat(s.icon_merchant),children:(0,a.jsx)("span",{children:"Icon"})}),(0,a.jsx)("div",{className:"col-9",children:(0,a.jsx)("h3",{children:"Merchant name"})})]}),(0,a.jsxs)(m,{className:"row short-padding rounded",children:[(0,a.jsx)("div",{className:"col-3",children:"\u603B\u91D1\u989D"}),(0,a.jsx)("div",{className:"col-9 text-end font-low-contrast",children:"1 USD = 0.9135 EUR"})]}),(0,a.jsx)("div",{className:c.pricetag,children:"405.51 EUR"}),(0,a.jsx)("div",{className:c.pricetagDesc,children:"455.00 USD"}),(0,a.jsxs)("div",{className:"row g-0 align-items-center ".concat(c.ticketDetailsRow),children:[(0,a.jsx)("div",{className:"col-2 text-center ".concat(c.icon," ").concat(s.green_icon),children:(0,a.jsx)("span",{children:"icon"})}),(0,a.jsxs)("div",{className:"col-4",children:[(0,a.jsx)("div",{children:"0.30 USD"}),(0,a.jsx)("div",{className:"font-low-contrast",children:"\u4F18\u60E0\u91D1\u989D"})]}),(0,a.jsx)("div",{className:"col-2 ".concat(c.icon," ").concat(s.orange_icon),children:(0,a.jsx)("span",{children:"icon"})}),(0,a.jsxs)("div",{className:"col-4",children:[(0,a.jsx)("div",{children:"6.00 USD"}),(0,a.jsx)("div",{className:"font-low-contrast",children:"\u7A0E"})]}),(0,a.jsx)("div",{className:"col-2 ".concat(c.icon," ").concat(s.blue_icon),children:(0,a.jsx)("span",{children:"icon"})}),(0,a.jsxs)("div",{className:"col-10",children:[(0,a.jsx)("div",{children:"4651651666116169"}),(0,a.jsx)("div",{className:"font-low-contrast",children:"\u8BA2\u5355\u53F7"})]})]}),(0,a.jsx)(m,{className:"row",children:"Los comentarios de esta cuenta"})]})})},N=_,p=function(r){var t=r.Global;return(0,a.jsx)("div",{className:"".concat(e.global," dark-template global container-fluid ").concat(t.layout),children:(0,a.jsxs)("div",{className:"row ".concat(e.globalRow),children:[(0,a.jsx)("div",{className:"col-12 col-md-4 col-xxl-3 ".concat(e.header),children:(0,a.jsx)(N,{})}),(0,a.jsx)("div",{className:"col-12 col-md-8 col-xxl-9 ".concat(e.main),children:(0,a.jsx)(l.Outlet,{})})]})})},b=(0,l.connect)(function(o){return o})(p)}}]);
